# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-11 04:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_friend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='friends',
            new_name='user',
        ),
    ]
