# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-11 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20170411_0441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='friend',
            field=models.ManyToManyField(null=True, related_name='_user_friend_+', to='manager.User'),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
