# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-11 03:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='friends',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
